### ISSUE TITLE
点击查看按钮跳转到列表页时不传递参数。

### ISSUE THREAD

**Issue by habitshine** [FlexZoom/Admin5#11]
看按钮进入的是一个列表页，首先跳转本身存在BUG需要刷新下才能进入，其次VUE那边对列表页没有做参数接收，只是把你的界面抓过来了，但是界面中的数据请求地址在请求的时候不带你传的参数，所以你的列表永远显示的是一样的数据。

**Comment by 383514580** [comment]
已解决
