### ISSUE TITLE
【路由】日报等模块路由

### ISSUE THREAD

**Issue by tt36999** [FlexZoom/Admin5#14]
日报
列表：/home/dailys/index->/dailys/index
列表：/home/dailys/show->/dailys/show
添加：/home/dailys/add->/dailys/add
修改：/home/dailys/edit->/dailys/edit
组织机构
列表：/home/department/index->/department/index
修改：/home/department/edit->/department/edit
添加：/home/department/add->/department/add
个人资料（需要可以修改）
修改：/home/personal/editpersonal->/personal/editpersonal

**Comment by 383514580** [comment]
ok, 发布版本后支持
