### ISSUE TITLE
编辑成功后跳转外链地址

### ISSUE THREAD

**Issue by fellowzhang** [FlexZoom/Admin5#15]
编辑页面，点击确定成功后，跳转外链地址，执行导出操作

**Comment by 383514580** [comment]
已完成,等待打包
数据结构如下
// 外部链接
{status:1, data: {link: "/xxx/xxx.php"},message: "xxxx"}

// 切换路由
{status:1, data: {path: "/home/x/xx", query: {id: 1}},message: "xxxx"}
