### ISSUE TITLE
列表页URL 可以带参数传递

### ISSUE THREAD

**Issue by z86722923** [FlexZoom/Admin5#30]
如
'data'=>[
                'table'=>$form->table([
                    //主键名称，可不传，默认为id
                    'primary'=>'id',
                    //表头定义规则
                    'header'=>[
                        [ "text" => "申请时间" , "key" =>"apply_time" ],
                        [ "text" => "员工姓名" , "key" =>"realname" ],
                        [ "text" => "员工英文名" , "key" =>"ename" ],
                        [ "text" => "金币数量",  "key" =>"apply_gold"]
                    ],
                    //表格头部按钮
                    'toolbar'=>[
                        // ['text'=>'添加', 'icon'=>'edit', 'url'=>'/golds/menusadd']
                    ],
                    //记录后方的操作按钮
                    'rowbar'=>[
                        ['text'=>'查看详情', 'icon'=>'edit', 'url'=>'/golds/listaaa?abc=1'](注：这里默认的page和limit和id的参数希望一起带着，最终提交的get请求应该是 www.xxx.com//golds/listaaa?abc=1&page=1&limit=1&id=1 )
                    ],
                    //数据请求地址
                    'ajax'=>'/golds/index?type=1'
                ])

**Comment by 383514580** [comment]
已解决
